package ru.kuramov.model;
// Generated 23.11.2016 16:21:21 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Edition generated by hbm2java
 */
@Entity
@Table(name="Edition",catalog="Catalog_IDEA")
@NamedQueries({
        @NamedQuery(name = "findEditionAll", query = "SELECT e FROM Edition e"),
        @NamedQuery(name = "findEditionByEdition", query = "SELECT e FROM Edition e WHERE e.edition = :edition")
})
public class Edition  implements java.io.Serializable {


    private Integer idEdition;
    private Catalog catalog;
    private String edition;
    private Set<Section> sections = new HashSet<Section>(0);

    public Edition() {
    }


    public Edition(Catalog catalog) {
        this.catalog = catalog;
    }
    public Edition(Catalog catalog, String edition, Set<Section> sections) {
        this.catalog = catalog;
        this.edition = edition;
        this.sections = sections;
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idEdition", unique=true, nullable=false)
    public Integer getIdEdition() {
        return this.idEdition;
    }

    public void setIdEdition(Integer idEdition) {
        this.idEdition = idEdition;
    }

    @ManyToOne(fetch=FetchType.LAZY, cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
    @JoinColumn(name="Catalog_idCatalog", nullable=false)
    public Catalog getCatalog() {
        return this.catalog;
    }

    public void setCatalog(Catalog catalog) {
        this.catalog = catalog;
    }


    @Column(name="edition", length=100)
    public String getEdition() {
        return this.edition;
    }

    public void setEdition(String edition) {
        this.edition = edition;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="edition")
    public Set<Section> getSections() {
        return this.sections;
    }

    public void setSections(Set<Section> sections) {
        this.sections = sections;
    }
}


